import type { Metadata } from "next";

import { Ysabeau_Infant } from "next/font/google";

import "./globals.css";
import { Toaster } from "sonner";

const ysabeauInfant = Ysabeau_Infant({
  subsets: ["latin"],
  variable: "--font-ysabeau-infant",
});

export const metadata: Metadata = {
  description: "Generated by create next app",
  icons: {
    icon: "/favicon-16x16.png",
  },
  title: "Халифа",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link href="/favicon.ico" rel="icon" sizes="any" />
        <link href="/icon?<generated>" rel="icon" sizes="<generated>" type="image/<generated>" />
      </head>
      <body className={`${ysabeauInfant.className} antialiased`}>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
