import type { Metadata } from "next";

import { Ysabeau_Infant } from "next/font/google";

import "./globals.css";
import Footer from "@/components/shared/footer";
import Navbar from "@/components/shared/navbar";

const ysabeauInfant = Ysabeau_Infant({
  subsets: ["latin"],
  variable: "--font-ysabeau-infant",
});

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Халифа",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ysabeauInfant.className} antialiased`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
